services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: "0:0"
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    volumes:
      - ./jenkins_home:/var/jenkins_home
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
